steps:
  - name: 'maven:3.8.3-openjdk-17'
    id: 'Build with Maven'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
          mvn clean install -DskipTests

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy Cloud Function'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
          gcloud functions deploy PublishMessage \
          --verbosity debug \
          --runtime java17 \
          --trigger-http \
          --allow-unauthenticated \
          --source=target \
          --entry-point=functions.PublishMessage \
          --region=us-central1

timeout: 1200s

options:
  logging: CLOUD_LOGGING_ONLY