steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - user-function-build
      - --entry-point=function.PubSubFunction
      - --region=us-central1
      - --source=.
      - --trigger-http
      - --runtime=java17
      - --memory=512MB
      - --timeout=90
      - --min-instances=0
      - --max-instances=1
      - --allow-unauthenticated
      - --service-account=bf-cloud-sa@primordial-veld-442819-k2.iam.gserviceaccount.com
      - --quiet
