steps:
  - name: maven:3.8.4-openjdk-17
    entrypoint: mvn
    args:
      - clean
      - package
    id: "Build JAR"

  - name: gcr.io/cloud-builders/gcloud
    args:
      - functions
      - deploy
      - "PubSubFunction" 
      - "--region=us-central1"
      - "--runtime=java17"
      - "--entry-point=function.PubSubFunction" 
      - "--trigger-http" 
      - "--set-env-vars=PUBSUB_TOPIC=bf-webhook,GCP_PROJECT=primordial-veld-442819-k2"
      - "--source=target/deploy"
    id: "Deploy Function"

artifacts:
  objects:
    location: gs://bf-cloud-functions-storage/cloud-functions/
    paths:
      - target/deploy/**
      
# Substitutions for parameterizing build details
substitutions:
  _PUBSUB_TOPIC: "bf-webhook"
  _GCP_PROJECT: "primordial-veld-442819-k2"

options:
  logging: CLOUD_LOGGING_ONLY